---
homebrew_user: "{{ admin_user }}"

homebrew_group: brew

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - { name: curl, install_options: "with-openssl" }
  - dnscrypt-proxy
  - {name: dnsmasq, install_options: "with-dnssec"}
  - gnupg
  - privoxy

homebrew_cask_apps:
  - avast-security
  - bitwarden
  - blockblock
  - dhs
  - kextviewer
  - knockknock
  - lockdown
  - lulu
  - netiquette
  - oversight
  - ransomewhere
  - reikey
  - security-growler
  - taskexplorer
  - whatsyoursign
