---
# homebrew_user: "{{ admin_user }}"

# homebrew_group: "brew"

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - dnscrypt-proxy
  - dnsmasq
  - gnupg
  - privoxy

homebrew_cask_apps:
  - avast-security
  - bitwarden
  - blockblock
  - dhs
  - kextviewr
  - knockknock
  - lockdown
  - lulu
  - netiquette
  - oversight
  - ransomwhere
  - reikey
  - security-growler
  - taskexplorer
  - whatsyoursign
