---
admin_user: "{{ ansible_user_id }}"

login_message: "This computer is configured and managed by Soren LLC. Contact us at https://soren.tech"

# homebrew_group: brew

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/services

homebrew_installed_packages:
  - bitwarden-cli
  - dnsmasq --with-dnssec
  - dnscrypt-proxy
  - gnupg 

homebrew_cask_apps:
  - bitwarden
  - blockblock
  - dhs
  - do-not-disturb
  - firefox
  - google-chrome
  - kextviewr
  - knockknock
  - lockdown
  - lulu
  - netiquette
  - oversight
  - ransomwhere
  - reikey
  - taskexplorer
  - whatsyoursign
