---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
    - include_tasks: tasks/curl.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - include_tasks: tasks/settings.yml
    - include_tasks: tasks/dns.yml
