---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_tasks: tasks/users.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['always']

  tasks:
    - include_tasks: tasks/settings.yml
    - include_tasks: tasks/cli.yml
