- name: install curl
  homebrew:
    name: curl
    install_options: with-openssl
    state: linked
    update_homebrew: yes

- name: configure curl
  fetch:
    src: https://raw.githubusercontent.com/drduh/config/master/curlrc
    dest: /Users/"{{ item }} "/.curlrc
    loop: "{{ users }}"

- name: configure dns packages
  fetch:
    src: https://raw.githubusercontent.com/drduh/config/master/"{{ item.src }}"
    dest: /usr/local/etc/"{{ item.dest }}"
    with_items:
      - name: dnscrypt-proxy
        src: dnscrypt-proxy.toml 
        dest: dnscrypt-proxy.toml
      - name: dnsmasq
        src: dnsmasq.conf 
        dest: dnsmasq.conf 
      - name: privoxy-config 
        src: privoxy/config 
        dest: privoxy/config
      - name: privoxy-user-action
        src: privoxy/user.action
        dest: privoxy/user.action 

- name: configure gnupg
  fetch:
    src: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
    dest: /Users/"{{ item }}"/.gpg.conf
    loop: "{{ users }}"

- name: start homebrew services
  shell: brew services start "{{ item }}"
  become: True
  loop:
    - dnscrypt-proxy
    - dnsmasq
    - privoxy

- name: change system DNS
  shell: networksetup --setdnsservers "{{ item }}" 127.0.0.1
  become: True
  loop:
    - "Wi-Fi"
    - "Ethernet"

- name: change system proxy
  shell: networksetup --setsecurewebproxy "{{ item }}" 127.0.0.1 8118
  become: True
  loop:
    - "Wi-Fi"
    - "Ethernet"
