---
- name: Clone Stephen Black Hosts
  git:
    repo: 'https://github.com/StevenBlack/hosts.git'
    dest: ~/.hosts
    depth: 1
    force: yes

- name: Install Hosts Updater Dependencies
  shell: cd ~/.hosts && pip3 install --user -r requirements.txt

- name: Generate Hosts File
  shell: cd ~/.hosts && python3 updateHostsFile.py --auto --replace --flush-dns-cache --extensions fakenews gambling 

- name: configure dns packages
  fetch:
    src: "files/{{ item.src }}"
    dest: "/usr/local/etc/{{ item.dest }}"
    flat: yes
  loop:
    - { src: dnscrypt-proxy.toml, dest: dnscrypt-proxy.toml }
    - { src: dnsmasq.conf, dest: dnsmasq.conf } 
    - { src: privoxy/config, dest: privoxy/config }
    - { src: privoxy/user.action, dest: privoxy/user.action } 

#- name: configure gnupg
#  fetch:
#    src: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
#    dest: /Users/"{{ item }}"/.gpg.conf
#    loop:
#      - "{{ admin_user }}"
#      - "{{ local_user }}"

- name: start homebrew services
  shell: "brew services start {{ item }}"
  become: True
  loop:
    - dnscrypt-proxy
    - dnsmasq
    - privoxy

- name: change Wi-Fi DNS servers
  shell: networksetup -setdnsservers "Wi-Fi" 127.0.0.1
  become: True

- name: change Ethernet DNS servers
  shell: networksetup -setdnsservers "Ethernet" 127.0.0.1
  become: True

- name: change system proxy
  shell: "networksetup -setsecurewebproxy {{ item }} 127.0.0.1 8118"
  become: True
  loop:
    - '"Wi-Fi"'
    - '"Ethernet"'
