---
- name: configure dns packages
  fetch:
    src: files/"{{ item.src }}"
    dest: /usr/local/etc/"{{ item.dest }}"
    with_items:
      - { src: dnscrypt-proxy.toml, dest: dnscrypt-proxy.toml }
      - { src: dnsmasq.conf, dest: dnsmasq.conf } 
      - { src: privoxy/config, dest: privoxy/config }
      - { src: privoxy/user.action, dest: privoxy/user.action } 

#- name: configure gnupg
#  fetch:
#    src: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
#    dest: /Users/"{{ item }}"/.gpg.conf
#    loop:
#      - "{{ admin_user }}"
#      - "{{ local_user }}"

- name: start homebrew services
  shell: brew services start "{{ item }}"
  become: True
  loop:
    - dnscrypt-proxy
    - dnsmasq
    - privoxy

- name: change system DNS
  shell: networksetup --setdnsservers "{{ item }}" 127.0.0.1
  become: True
  loop:
    - "Wi-Fi"
    - "Ethernet"

- name: change system proxy
  shell: networksetup --setsecurewebproxy "{{ item }}" 127.0.0.1 8118
  become: True
  loop:
    - "Wi-Fi"
    - "Ethernet"
