---
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_installed_packages }}"
  tags: ["homebrew"]
  
- name: Install homebrew casks
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_cask_apps }}"
  ignore_errors: yes
  tags: ["homebrew"]
