- name: Set baseline security settings
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type|default('bool') }}"
    value: "{{ item.value|default('true') }}"
  become: yes
  loop:
    - { description: "CIS 1.2 Enable Auto Updates", domain: com.apple.SoftwareUpdate, key: com.apple.SoftwareUpdate }
    - { description: "CIS 1.2 Enable Auto Updates", domain: com.apple.SoftwareUpdate, key: ScheduleFrequency, type: int, value: 1 }
    - { description: "CIS 1.2 Enable Auto Updates", domain: com.apple.SoftwareUpdate, key: AutomaticCheckEnabled }
    - { description: "CIS 1.2-1.3 Enable Auto Updates", domain: com.apple.SoftwareUpdate, key: AutomaticDownload, type: int, value: 1 }
    - { description: "CIS 1.4 Enable app update installs", domain: com.apple.commerce, key: AutoUpdate }
    - { description: "CIS 1.5 Enable system data files and security update installs", domain: com.apple.SoftwareUpdate, key: ConfigDataInstall }
    - { description: "CIS 1.5 Enable system data files and security update installs", domain: com.apple.SoftwareUpdate, key: CriticalUpdateInstall, type: int, value: 1 }
    - { desciption: "Enable Updates Requiring a Restart", domain: com.apple.commerce, key: AutoUpdateRestartRequired }
    # - { description: "CIS 2.1.1 Turn off Bluetooth if no paired devices exist", }
    # - { description: "CIS 2.1.3 Show bluetooth status in menu bar", }
    # - { description: "CIS 2.2.1 Set time and date automatically", }
    # - { description: "CIS 2.3.1 Set inactivity interval for screen saver", }
    # - { description: "CIS 2.3.2-3 Set a screen corner to start screen saver", }
    # - { description: "CIS 2.4.1 Disable Remote Apple Events", }
    # - { description: "CIS 2.4.2 Disable Internet Sharing", }
    # - { description: "CIS 2.4.3 Disable Screen Sharing", }
    # - { description: "CIS 2.4.4 Disable Printer Sharing", }
    # - { description: "CIS 2.4.5 Disable Remote Login," }
    # - { description: "CIS 2.4.6 Disable DVD or CD Sharing", }
    # - { description: "CIS 2.4.7 Disable Bluetooth Sharing", }
    # - { description: "CIS 2.4.8 Disable File Sharing", }
    # - { description: "CIS 2.4.9 Disable Remote Management", }
    # - { description: "CIS 2.4.10 Disable Content Caching", }
    # - { description: "CIS 2.4.11 Disable Media Sharing", }
    # - { description: "CIS 2.5.2 Enable Gatekeeper", }
    - { description: "CIS 2.5.3 Enable Firewall", domain: /Library/Preferences/com.apple.alf, key: globalstate, type: int, value: 1 }
    # - { description: "CIS 2.5.4 Enable Firewall Stealth Mode", }
    # - { description: "CIS 2.5.8 Disable sending diagnostic and usage data to Apple", }
    # - { description: "CIS 2.6.2 Disallow iCloud Keychain", }
    # - { description: "CIS 2.6.3 Disallow iCloud Drive", }
    - { description: "CIS 2.6.4 Disallow iCloud Document Sync", domain: NSGlobalDomain, key: NSDocumentSaveNewDocumentsToCloud, value: false }
    # - { description: "CIS 2.6.5 Disallow iCloud Desktop Sync", }
    - { description: "CIS 2.9 Enable secure keyboard entry in terminal.app", domain: com.apple.Terminal, key: SecureKeyboardEntry }
    - { description: "CIS 2.10 Securely empty trash", domain: com.apple.finder, key: EmptyTrashSecurely }   
    # - { description: "CIS 2.12 Disable wake for network access and power nap", }
    # - { description: "CIS 3.1 Enable security auditing", }
    # - { description: "CIS 3.3 Ensure security auditing retention", }
    # - { description: "CIS 3.4 Control access to audit records", }
    # - { description: "CIS 3.5 Retain install.log for 365 days", }
    # - { description: "CIS 3.6 Ensure firewall is configured to log", }
    - { description: "CIS 4.1 Disable Bonjour advertising service", domain: com.apple.mDNSResponder key: NoMulticastAdvertisements }
    # - { description: "CIS 4.2 Show WiFi status in menu bar", }
    # - { description: "CIS 4.4 Ensure http server is not running", }
    # - { description: "CIS 4.5 Ensure nfs server is not running", }
    # - { description: "CIS 5.3 Reduce the sudo timeout period", }
    # - { description: "CIS 5.7 Do not enable the root account", }
    # - { description: "CIS 5.8 Disable automatic login", }
    - { description: "CIS 5.9 Reauire a password to wake the computer from sleep or screen saver", domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
    - { description: "CIS 5.9 Reauire a password to wake the computer from sleep or screen saver", domain: com.apple.screensaver, key: askForPasswordDelay, type: int, value: 0 }
    # - { 
    - { domain: com.apple.finder, key: AppleShowAllFiles }
    - { domain: NSGlobalDomain, key: AppleShowAllExtensions }
    
    - { domain: /Library/Preferences/SystemConfiguration/com.apple.captive.control.plist, key: Active, value: false }
    - { 
    - { domain: com.apple.Safari, key: UniversalSearchEnabled, value: false }
    - { domain: com.apple.Safari, key: SuppressSearchSuggestions }
    - { domain: com.apple.Safari, key: AutoOpenSafeDownloads, value: false }
    - { domain: com.apple.Safari, key: WarnAboutFraudulentWebsites }
    - { domain: com.apple.Safari, key: SendDoNotTrackHTTPHeader }

    
    
    - {  }
    


- name: Configure Firefox Policies
  fetch:
    src: "files/firefox.policies.json"
    dest: "/Applications/Firefox.app/Contents/Resources/distribution/policies.json"

