---
- name: Verify admin user is present
  user: "{{ admin_user|default(admin) }}"
  groups: admin,brew
  state: present
- name: Verify local user is present
  user: "{{ local_user|default(local) }}"
  groups: brew
  state: present
